
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 24 22:12:53 EST 2014
//----------------------------------------------------

package compiler488.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 44;
  public static final int WHEN = 23;
  public static final int PUT = 14;
  public static final int L_PAREN = 29;
  public static final int INTEGER = 3;
  public static final int GREATER = 36;
  public static final int R_SQUARE = 32;
  public static final int REPEAT = 16;
  public static final int R_PAREN = 30;
  public static final int FORWARD = 9;
  public static final int MINUS = 42;
  public static final int LESS = 37;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int INTCONST = 47;
  public static final int OR = 25;
  public static final int COMMA = 38;
  public static final int R_CURLEY = 34;
  public static final int GET = 12;
  public static final int FI = 8;
  public static final int UNTIL = 17;
  public static final int PLUS = 41;
  public static final int EXIT = 7;
  public static final int IF = 11;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 21;
  public static final int EQUAL = 35;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int NEWLINE = 19;
  public static final int IDENT = 46;
  public static final int TIMES = 43;
  public static final int COLON = 40;
  public static final int ELSE = 5;
  public static final int FUNC = 10;
  public static final int L_SQUARE = 31;
  public static final int WHILE = 15;
  public static final int THEN = 22;
  public static final int TEXTCONST = 48;
  public static final int END = 6;
  public static final int QUESTION = 45;
  public static final int L_CURLEY = 33;
  public static final int FALSE = 28;
  public static final int VAR = 18;
  public static final int PROCEDURE = 13;
  public static final int DO = 4;
  public static final int RESULT = 20;
}

